### ISSUE TITLE
Text translation that once worked now does not work

### ISSUE THREAD

**Issue by ecuracosta** [nidhaloff/deep_translator#19]
* deep_translator version: 1.1.7
* Python version: 3.8.3
* Operating System: Manjaro 20.0.3

I'm trying to semi-automatize an HTML page using BeautifulSoup.
I was very happy with deep-translator until something strange happened...

It rises 'TranslationNotFound' with some text that was already working!

```
text = 'If you are a school administrator or local official who has control over school opening decisions, we strongly urge you to keep schools closed until there is no more community transmission of the virus. There must be no more transmission of the virus in your community and the surrounding areas for 14 days. If you would like more guidance on why reopening schools is dangerous and how to talk to students, teachers, parents and staff, EndCoronavirus.org is here to help.Please contact us for more information.'

GoogleTranslator(source='auto', target='spanish').translate(text=tag.text)
```

Traceback:

```
TranslationNotFound                       Traceback (most recent call last)
<ipython-input-8-466242e1794e> in <module>
      1 # Using deep_translator with Google's engine (spanish)
----> 2 traslated = GoogleTranslator(source='auto', target='spanish').translate(text=tag.text)
      3 traslated

~/.local/lib/python3.8/site-packages/deep_translator/google_trans.py in translate(self, text, **kwargs)
     78             if not element:
     79                 # raise ElementNotFoundInGetRequest(element)
---> 80                 raise TranslationNotFound(text)
     81 
     82             return element.get_text(strip=True)

TranslationNotFound: If you are a school administrator or local official who has control over school opening decisions, we strongly urge you to keep schools closed until there is no more community transmission of the virus. There must be no more transmission of the virus in your community and the surrounding areas for 14 days. If you would like more guidance on why reopening schools is dangerous and how to talk to students, teachers, parents and staff, EndCoronavirus.org is here to help.Please contact us for more information. --> No translation was found using the current translator. Try another translator?
```

Maybe I exceeded the max translations allowed? It should be unlimited, right?

And when I use 'MyMemoryTranslator' I get:

 'QUERY LENGTH LIMIT EXCEDEED. MAX ALLOWED QUERY : 500 CHARS'

Also unexpected!

**Comment by ecuracosta** [comment]
Now it's working again!!! But I did nothing.

**Comment by nidhaloff** [comment]
@ecuracosta Thanks for opening the issue. The translations are definitely unlimited (that is also the goal of the package) so that's not the problem. The max characters allowed in the google translator are 5000. So your text length is fine in this case since it does not exceed the limit. Therefore, I'm guessing this have nothing to do with the package per se. 

Notice that this can happen during the request. The deep_translator is requesting the translation from google under the hood. So if something went wrong with the response then it would probably throw a **TranslationNotFound** error, which is certainly why you are having this behavior since it worked the second time without changing nothing.

Your issue is very helpful! I need to actually check the response status and if it's not 200 then I should throw another exception and not the TranslationNotFound exception in this case since it's confusing. Also, I need to update the max length characters for mymemory to 500 and catch exceptions that surpass this. I will work on this **today**

**Comment by ecuracosta** [comment]
Good to know it help! Thanks for your work, deep_translator is great!!!

**Comment by nidhaloff** [comment]
@ecuracosta Thanks I appreciate it. I released a new version where I added a check on request status code and other checks on text length in order to validate the inputs.

Like I said in your case, I'm certain that the issue is due to some connections problem and therefore the request was not successful. If it happens now, the deep_translator will throw an **RequestError** and request you to check if you have any connection problems and then try again.

I will close the issue but feel free to open it again or make a new issue if you encountered any suspicious behaviors

**Comment by ecuracosta** [comment]
Sorry for reopening. Definitely not a connection problem.
This is happening when I do to much requests.
I tried with a VPN but the problem remains.
If I wait some time and then try again, it works.

Any idea?

**Comment by ecuracosta** [comment]
VPN works. But it won't do the job in my case, I'll go for your delay suggestion, many thanks!

**Comment by ecuracosta** [comment]
Sorry I reopened again, but using "sleep" with the quota limits that you showed is not working for me. I tried finding more limits , like limits by day, but didn't worked either (https://cloud.google.com/translate/quotas). I think using proxies would be a possible solution if you are using "requests" module to make the translations: 

https://www.scrapehero.com/how-to-rotate-proxies-and-ip-addresses-using-python-3/

Would you tell me if this is possible? Or you are using a Google Account for this? Thanks!

**Comment by nidhaloff** [comment]
@ecuracosta I will investigate this

**Comment by ecuracosta** [comment]
> @ecuracosta I will investigate this

Sorry, don't want to bother, do you have any news? Something I can help / test?

Would be nice to have a clear idea about the request quotas or to solve this with a proxy or VPN.

**Comment by MarceloDiefenbach** [comment]
im having this issue when deploy on heroku. when i run locally its work but when deploy give me an error
